### PR TITLE
critical apparatus 000-000-019-098

### PR DESCRIPTION
**Pull request by mmjseclark**

### CODE REVIEW

**Comment by Ramona2020** [comment]
Hi!  Just one minor edit in line 12 of the first resp statement, change "Encoded by" to "Basic Markup".  Everything else looks spot on :smile:

**Comment by Ramona2020** [comment]
Hi Sophia,
Before I can pull in your changes, I have a few corrections for you in the following poems:
FDM-058-074-000-076
FDM-063-101-000-125
FDM-069-100-000-124
FDM-070-099-000-123
FDM-073-072-000-074
FDM-093-104-000-128

The problem is the critical apparatus element.You're using two `<rdg>` elements when you only really need to use one.  For example in FDM--069-100-000-124 at line 106 you have the following:
`<app>
<lem wit="U1857"></lem>
<rdg wit="FDM1861">,</rdg>
<rdg wit="FDM1868">,</rdg>
</app>`
Both of the witnesses show the same change and that information can be expressed in one `<rdg>` element like so:
`<app>
<lem wit="U1857"></lem>
<rdg wit="FDM1861 FDM1868">,</rdg>
</app>`
You can list multiple witnesses in the attribute by just adding a space between them.
Also, only use the `<rdg>` element to indicate textual differences from the lemma.  See poem FMD-073-072-000-074, line 128:
`<app>
<lem wit="U1857">;</lem>
<rdg wit="FDM1861">;</rdg>
<rdg wit="FDM1868">!</rdg>
</app>`
Since FDM1861 is the same as U1857 you don't need to do anything there, just record the difference in FDM1868.

Let me know if you have any questions :smile: 
Ramona

**Comment by mmjseclark** [comment]
Hi Ramona!
Thanks! I’ll have that done before our meeting next Friday and resubmit.
Best,
Sophia

**Comment by Ramona2020** [comment]
Awesome!

**Comment by mmjseclark** [comment]
Hi Ramona,
I have made the the Critical Apparatus corrections to the list you sent me and synced them with Purple Kitty.
See you later!
Sophia

**Pull request merged**
