### PR TITLE
3 Poems - basic markup

### PR DESCRIPTION
**Pull request by graytl**
Basic markup for three poems - Le Serpent qui danse, Avec ses vetements ondoyants et nacres, L'Albatros.

### CODE REVIEW

**Comment by Ramona2020** [comment]
Hi Teresa,
Just a few things to correct.  1. For the following poems,  FDM-025-027-000-028, FDM-026-028-000-029, FDM-027-029-000-030, FDM-000-002-000-002, FDM-042-046-000-047, change contents of the```<resp>``` element in the header to **Basic Markup**.

2. For FDM-025-027-000-028 and FDM-042-043-000-047 the ```<div>``` element needs to be edited to ```<div type="poem" subtype="sonnet">```

**Comment by graytl** [comment]
Thanks, Ramona.  I'll get this corrected as soon as I can.

I'm actually out sick today, so I won't be able to make the meeting this afternoon.  Will you let me know what gets decided on the poems with multiple parts?

Thanks,

Teresa
________________________________

**Comment by graytl** [comment]
Hi Ramona,

Sorry, I’ve been working on exhibits so I just got to this.

I’ve just synced all the changes except FDM-042-043-000-047.  I didn’t see this one on Github.  Did I miss it somewhere?  Or is this supposed to be FDM-042-046-000-047?

Thanks,

Teresa

**Comment by Ramona2020** [comment]
Hi Teresa,

It is supposed to be FDM-042-046-000-047.  I must have mistyped a 3 for the 6.  

Ramona

**Comment by graytl** [comment]
Great.  I’ll correct this after I get off the desk.

Teresa

**Comment by graytl** [comment]
Done!

Teresa

**Pull request merged**
