### PR TITLE
Add critical apparatus to 3 FDM poems

### PR DESCRIPTION
**Pull request by sterkenburgsara**

### CODE REVIEW

**Comment by Ramona2020** [comment]
Sara,
Don't hate me but, we changed how we are dealing with ligatures.  Now we are using the choice element for ligatures that appear in the text.  There is a sample in the wiki under *Working with Ligatures*.

FDM-026-028-000-029, Le Serpent Qui Danse, see line 36 of the poem.
FDM-068-084-000-106, L'Irremediable, see line 4 in part one of the poem and line 2 in part two of the poem.
Everything else looks great :smile_cat: 
Ramona

**Comment by sterkenburgsara** [comment]
Gah!! Ok - I will change when I get back on Tuesday. Thanks :)

**Comment by Ramona2020** [comment]
No worries!  We seem to keep changing our mind about things :)

**Comment by sterkenburgsara** [comment]
Ok fixed - merge please :)

**Comment by sterkenburgsara** [comment]
ok fixed - merge please :)

**Pull request merged**
