### PR TITLE
Couvercle poem

### PR DESCRIPTION
**Pull request by ZoraBreeding**

### CODE REVIEW

**Comment by Ramona2020** [comment]
I see the pull request!  I'll work on it soon

**Comment by ZoraBreeding** [comment]
I am trying to create a pull request for Le Soleil, but it seems to have just added itself on the the existing pull request for Couvercle. If you don't see two poems, let me know.  Also, Le Soleil had no changes between the 3 editions it appeared in. Love.

**Comment by Ramona2020** [comment]
No crisis. When you have an open pull request any commits you make after submitting the pull request will get attached to the pull request.   I can see it on github.   I'll stop being a slacker on Monday. 
Ramona

**Comment by ZoraBreeding** [comment]
I have change the poem id of Hymn from 000-000-000-094 to 000-000-010-094. Probably need to delete the file 000-000-000-094.  I didn't know how to overwrite a file with a new file name.

**Pull request merged**
