### PR TITLE
new poems January (2nd try)

### PR DESCRIPTION
**Pull request by panterra**

### CODE REVIEW

**Comment by Ramona2020** [comment]
Rebecca,

Before I can merge I need you to add the idno in the header for both poems.  Make the changes and commit them in your repository and when you sync purple kitty and the cloud, the changes will automatically get added to this pull request.

**Comment by panterra** [comment]
Hi Ramona,

Thanks for catching this! I added the ID, committed changes, and synced, so
I think it should show up in my pull request now.

Best,

Rebecca



--------------------------------------------------------------------------------------
Rebecca Panter
Graduate Student Affiliate, Center for Second Language Studies
ABD, Department of Germanic & Slavic Languages
Vanderbilt University
Nashville, TN

**Comment by Ramona2020** [comment]
We are good to go.  I'm going to merge!

**Comment by panterra** [comment]
Phew! Glad it worked. I'm having to recollect my TEI skills after the
winter break, it seems. Thanks for the help!


--------------------------------------------------------------------------------------
Rebecca Panter
Graduate Student Affiliate, Center for Second Language Studies
ABD, Department of Germanic & Slavic Languages
Vanderbilt University
Nashville, TN

**Pull request merged**
